name: Python Package & PyPI Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -e observatory-platform
          pip install -e observatory-dags
          pip install -e observatory-reports

      - name: Build packages
        run: |
          cd observatory-platform
          python3 setup.py sdist

          cd ../observatory-dags
          python3 setup.py sdist

          cd ../observatory-reports
          python3 setup.py sdist

          cd ../

      - name: Publish observatory-platform
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: observatory-platform/dist/

      - name: Publish observatory-dags
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.pypi_password }}
            packages_dir: observatory-dags/dist/

      - name: Publish observatory-reports
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
          uses: pypa/gh-action-pypi-publish@master
          with:
            user: __token__
            password: ${{ secrets.pypi_password }}
            packages_dir: observatory-reports/dist/


